/* connection.c generated by valac 0.18.1, the Vala compiler
 * generated from connection.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <telepathy-glib/telepathy-glib.h>
#include "connection-manager.h"
#include "protocol.h"


G_DEFINE_TYPE(LwqqConnectionManager, lwqq_connection_manager, TP_TYPE_BASE_CONNECTION_MANAGER)

static void 
lwqq_connection_manager_init(LwqqConnectionManager *obj) {
}

static void lwqq_connection_manager_constructed (GObject *object) {
	TpBaseConnectionManager *base = (TpBaseConnectionManager *) object;
	TpBaseProtocol *p;
	void (*constructed) (GObject *) = ((GObjectClass *) lwqq_connection_manager_parent_class)->constructed;

	if (constructed != NULL)
		constructed (object);

    p = g_object_new (LWQQ_TYPE_PROTOCOL,
            "name", PROTOCOL_NAME,
            NULL);

	tp_base_connection_manager_add_protocol (base, p);
    //let it auto released
	g_object_unref (p);
}

static void lwqq_connection_manager_class_init(LwqqConnectionManagerClass *klass) {
	GObjectClass *object_class = G_OBJECT_CLASS (klass);
	TpBaseConnectionManagerClass *parent_class = TP_BASE_CONNECTION_MANAGER_CLASS(klass);

	parent_class->cm_dbus_name = "tp_lwqq";

	object_class->constructed = lwqq_connection_manager_constructed;
}
